### ISSUE TITLE
Ghost effect in outputs

### ISSUE THREAD

**Issue by rakesh-reddy95** [CXH-Research/DocShadow-SD7K#8]
Hi @xuhangc @zinuoli , 
I see the ghost effect remaining in the outputs after the shadow removal on unseen datasets. How can we resolve this issue? 

Example:
Input:
![IMG20231017123235](https://github.com/CXH-Research/DocShadow-SD7K/assets/20672248/003bc180-250f-4e22-b4c6-82f9f7e93882)

Output:
![IMG20231017123235_pred](https://github.com/CXH-Research/DocShadow-SD7K/assets/20672248/94d9495d-d849-4f23-b2f7-58e76145e35b)

**Comment by zinuoli** [comment]
Hi, I recommend you to make the input data similar to the domain of pretrained dataset like SD7K. However, ghost is a challenge in every shadow removal method. We could not promise a perfect performance with our current method, we will improve the model in the future.

**Comment by rakesh-reddy95** [comment]
@zinuoli However these images are similar to SD7K but the ghost effect remains in this images but not in SD7K.

**Comment by zinuoli** [comment]
Hi, this could happen in every shadow removal method. You may consider collecting a small dataset and fine-tune our model on your specific domain. Also, you can try other method trained on SD7K. I guess it's because for computer its domain is not similar to SD7K.

**Comment by zinuoli** [comment]
There is indeed some ghost remains in the predicted result, even in the SD7K:
![IMG_0148](https://github.com/CXH-Research/DocShadow-SD7K/assets/94612909/4a2aaa50-8bfa-4cbb-8e39-184d80423677)
You can refer to the results we release, I believe this is what we should improve in the future.

**Comment by zinuoli** [comment]
Hi @rakesh-reddy95, you may test the input data using different weight trained on different dataset. I tested the following image using **Jung.pth**, they are much better:
![1](https://github.com/CXH-Research/DocShadow-SD7K/assets/94612909/e3c0d52b-eec6-47cf-a5b4-90fb35180a82)

I strongly believe it's because domain gap. However, the ghost is still a big challenge remaining in the field of shadow removal, and in our future work we will improve it.

**Comment by zinuoli** [comment]
Issue closed due to no further response, feel free to open it again.
